#!/bin/bash

# 引数がない場合もしくは--helpの場合
if [ $# = 0 ] || [ "$1" = "--help" ]; then
    echo -en "\033[32mroulette - 自作ルーレットスクリプト\033[m\n\n"
    echo -e "\033[33mDescription:\033[m"
    echo -e "  引数として渡した要素の中からランダムに１つ選択するルーレットを回すスクリプト\n"
    echo -e "\033[33mArguments::\033[m"
    echo -e "  任意の個数\n"
    echo -e "\033[33mOptions:\033[m"
    echo -e "  \033[32m--help\033[m      この表示を出力\n"
    echo -e "\033[33mUsage:\033[m"
    echo -e "  \033[32mroulette\033[m p1 p2 p3 p4 p5 p6 p7"
    exit 0
fi

echo -e "\033[32mルーレット\033[m\n"

MAX_TIME=5

file_array=($@)
count=${#file_array[@]}
for item in ${file_array[@]}; do
    echo -n "$item  "
done
echo ""

rand=$(( $RANDOM % 100 ))
rouletSec=$(( $MAX_TIME + $rand ))
restSec=$rouletSec

countDownSpeed=2

lightPoint=0
while :
do
    c=0
    for item in ${file_array[@]}; do
	if [ $c = $lightPoint ]; then
	    for ((i=0; $i<${#item}; ++i)){
		    echo -en "\033[32m=\033[m"
		};
		echo -n "  "
	else
	    for ((i=0; $i<${#item}; ++i)){
		    echo -en "\033[33m_\033[m"
		};
		echo -n "  "
	fi
	c=$(( $c + 1 ))
    done
    lightPoint=$(( $lightPoint + 1 ))
    if [ $lightPoint = $count ]; then
	lightPoint=0
    fi
    printf '\r'
    restSec=$(( $restSec - $countDownSpeed ))
    if [ $restSec -lt 0 ]; then
	sleep 1
	echo ""
	if [ $lightPoint = 0 ]; then
	    lightPoint=$(( $count -1 ))
	else
	    lightPoint=$(( $lightPoint -1 ))
	fi
	echo ""
	echo "*********************************************"
	echo -e "*** 当選は ...  \033[31m${file_array[$lightPoint]}\033[m  です！"
	echo "*********************************************"
	exit 1
    elif [ $restSec -lt 10 ]; then
	sleep .2
	countDownSpeed=3
    elif [ $restSec -lt 100 ]; then
	sleep .12
	countDownSpeed=5
    elif [ $restSec -lt 200 ]; then
	sleep .1
	countDownSpeed=7
    elif [ $restSec -lt 300 ]; then
	sleep .08
    elif [ $restSec -lt 400 ]; then
	sleep .06
    elif [ $restSec -lt 450 ]; then
	sleep .04
    else
	sleep .01
    fi
done
echo ""
exit 0
